name: Build, Test and Deploy

on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:scripts

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
