name: Build, Test and Deploy

on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install
        run: npm ci

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Lint
          run: npm run lint:scripts

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: npm run build
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: npm run test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist

